name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.4.0

      - run: dotnet build

      - run: dotnet test --no-build --logger "trx;LogFilePrefix=tests" --results-directory "./coverage"

      - uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: .NET Tests
          path: ./coverage/*.trx
          reporter: dotnet-trx
